development:
  adapter: sqlite3
  database: db/book-development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/book-test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/book-production.sqlite3
  pool: 5
  timeout: 5000

